runtime: nodejs16
env: standard
entrypoint: npm run dev

# App Engine will look for your package.json file in the root of your application and install your dependencies
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
